[tool.poetry]
name = "runner-default"
version = "0.0.0"
description = "Default runner environment for the beet bot."
authors = ["Valentin Berlier <berlier.v@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Pillow = "^9.1.1"
beet = ">=0.68.2"
lectern = ">=0.24.0"
mecha = ">=0.54.2"
bolt = ">=0.8.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
