name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  main:
    name: Test and release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install pnpm
        run: npm install pnpm@latest -g
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build
      - name: Lint packages
        run: pnpm lint
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: action@github.com
          GIT_COMMITTER_NAME: github-actions
          GIT_COMMITTER_EMAIL: action@github.com
        run: pnpm release-dry
